### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by Janterra** [sapphic-wallflower/little-sisters-room#4]
Unsure if these were intentionally removed during an update, but the pages at 

[https://www.sapphic.dog/SSHP/kinklist.html](https://www.sapphic.dog/SSHP/kinklist.html)
and
[https://www.sapphic.dog/SSHP/blank_ultimate_infograph.png](https://www.sapphic.dog/SSHP/blank_ultimate_infograph.png)
are both leading to the 404 page.

**Comment by sapphic-wallflower** [comment]
@Janterra You can find the kinklist here: https://www.sapphic.dog/projects/kinklist.html. The infograph is no longer be hosted.

Thank you so much for the report <3
